Connector: IssacSim -> Ignition
ignitionrobotics/ign-omni pull request #16
Opened 2022-02-28 17:28 UTC by ahcorde

Signed-off-by: ahcorde <ahcorde@gmail.com>
# 🎉 New feature

## Summary

Communication between IssacSim -> Ignition.

Added a flag to check if the pose are set by Ignition or IssacSim

If you test this PR you might find some issue relative to this issue https://github.com/ignitionrobotics/ign-gazebo/issues/1358

## Checklist
- [ ] Signed all commits for DCO
- [ ] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

2022-03-01 07:22 UTC, koonpeng reviewed
Some questions regarding the `simulatorPoses` flag.

Should it only affect the poses or should we turn off ignition->omniverse completely? From what I understand on the code, it looks like a mix currently where if ignition is the controller, the entire omni->ign code path is disabled, but when omniverse is the controller, only updating of composes from ign->omni is disabled, adding, deleting of models, updating scalings, material etc is still enabled.

Operations other than poses in theory can cause loops as well, if we add a model in ign, it will add a subtree in usd, which causes a change event, which causes a ign request to add a model and so on. Same for operations like changing a model's scale, it's material properties etc.

2022-03-01 07:22 UTC, koonpeng commented on source/ignition_live/main.cpp
> +      ->required();
Not sure on the CLI11 feature set, but if it supports it, we should use enums.

2022-03-01 07:22 UTC, koonpeng commented on source/ignition_live/Scene.cpp
> +  if (this->ignitionControlPoses)
Would it be better to turn off subscription to the scene, joints and poses instead?

2022-03-01 07:22 UTC, koonpeng commented on source/ignition_live/Scene.cpp
> +    // TODO: disabled omniverse -> ignition sync to focus on ignition -> omniverse
Can this TODO be considered done with this pr?

2022-03-03 02:58 UTC, koonpeng commented
I'm getting service call timeout on the connector

```
[Dbg] [FUSDNoticeListener.hpp:234] path /shapes/box/box_link/box_visual/geometry.xformOp:translate
[Err] [FUSDNoticeListener.hpp:281] Service call timed out
[Dbg] [FUSDNoticeListener.hpp:234] path /shapes/box/box_link/box_visual/geometry.xformOp:translate
[Err] [FUSDNoticeListener.hpp:281] Service call timed out
[Dbg] [FUSDNoticeListener.hpp:234] path /shapes/box/box_link/box_visual/geometry.xformOp:translate
```

There are also errors on ignition

```
[Err] [UserCommands.cc:1337] Unable to update the pose for entity id:[0], name[geometry]
[Err] [UserCommands.cc:1337] Unable to update the pose for entity id:[0], name[geometry]
[Err] [UserCommands.cc:1337] Unable to update the pose for entity id:[0], name[geometry]
[Err] [UserCommands.cc:1337] Unable to update the pose for entity id:[0], name[geometry]
```

---

I notice ignition physics is still running when isaacsim updates a pose, in theory this could lead to conflicting states. I can't test this now because I had to re-install omniverse to fix some other issues and downloads are down so I can't re-install isaacsim.

2022-03-16 22:11 UTC, ahcorde commented
@koonpeng I was testing your changes, and I'm facing this issue. Translations look wrong

![ign-omni-error1](https://user-images.githubusercontent.com/1933907/158699676-eb668991-cc55-44db-9ecd-26ac4cc85f8a.gif)

You need this change in ign-gazebo https://github.com/ignitionrobotics/ign-gazebo/pull/1394

2022-03-17 21:01 UTC, ahcorde commented
I fixed the pose:
![fixed_pose_ign-omni](https://user-images.githubusercontent.com/1933907/158894481-f04607f5-30f9-47f9-9897-8a7f01b1b596.gif)

2022-03-17 21:05 UTC, ahcorde commented
But we are facing another issue. Issac Sim dos not provide the joint angle, we can only see changes in the links

Require: https://github.com/ignitionrobotics/ign-gazebo/pull/1394

I tried to implement something to calculate the joint angle but it's wrong https://github.com/ignitionrobotics/ign-omni/pull/16/commits/af1daca5967b8a829cec7cfe2c1477e3c3897754

![panda_wrong_angle](https://user-images.githubusercontent.com/1933907/158895055-1a2edb32-72d0-4a80-9a5d-4575ecbc2ef4.gif)

2022-03-18 09:05 UTC, koonpeng commented
> But we are facing another issue. Issac Sim dos not provide the joint angle, we can only see changes in the links
> 
> Require: [ignitionrobotics/ign-gazebo#1394](https://github.com/ignitionrobotics/ign-gazebo/pull/1394)
> 
> I tried to implement something to calculate the joint angle but it's wrong [af1daca](https://github.com/ignitionrobotics/ign-omni/commit/af1daca5967b8a829cec7cfe2c1477e3c3897754)
> 

Wasn't able to try this yet? I'm assuming this is the simulation being ran? https://docs.omniverse.nvidia.com/app_isaacsim/app_isaacsim/tutorial_ros_moveit.html

Tried to follow the tutorial but getting 404 errors when installing some ros packages.

2022-03-18 22:05 UTC, ahcorde commented
to test this you can run this script using ROS 1:

You should add the following ROS plugins: `Clock`, `Tree pose` and `Joint state`

<details>

```
#!/usr/bin/env python
# Copyright (c) 2020-2021, NVIDIA CORPORATION.  All rights reserved.
#
# NVIDIA CORPORATION and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA CORPORATION is strictly prohibited.

import rospy
from sensor_msgs.msg import JointState
import numpy as np
import time

rospy.init_node("test_rosbridge", anonymous=True)

pub = rospy.Publisher("/joint_command", JointState, queue_size=10)
joint_state = JointState()

joint_state.name = [
  "panda_joint1",
  "panda_joint2",
  "panda_joint3",
  "panda_joint4",
  "panda_joint5",
  "panda_joint6",
  "panda_joint7",
  "panda_finger_joint1",
  "panda_finger_joint2"
]

num_joints = len(joint_state.name)


# make sure kit's editor is playing for receiving messages ##

joint_state.position = np.array([0.0] * num_joints)
default_joints = [0.0, 1.57, 0.707, 0.707, 0, 3.1416, 0, 0, 0]

# limiting the movements to a smaller range (this is not the range of the robot, just the range of the movement
max_joints = np.array(default_joints) + 0.707
min_joints = np.array(default_joints) - 0.07

# position control the robot to wiggle around each joint
time_start = time.time()
rate = rospy.Rate(20)
while not rospy.is_shutdown():
    joint_state.position = [45.0*3.1416/180.0,
                            15.0*3.1416/180.0,
                            35.0*3.1416/180.0,
                            80.0*3.1416/180.0,
                            10.0*3.1416/180.0,
                            30.0*3.1416/180.0,
                            20.0*3.1416/180.0, 0, 0]
    joint_state.position = np.sin(time.time() - time_start) * (max_joints - min_joints) * 0.5 + default_joints
    #joint_state.position = default_joints
    pub.publish(joint_state)
    rate.sleep()
```

</details>

2022-03-22 07:23 UTC, koonpeng commented
managed to run the sim in isaac but wasn't able to get the connector to work


https://user-images.githubusercontent.com/45189696/159428359-443016af-98bb-45db-a673-9e45564f0d61.mp4

ignition logs
```
<same>
[Err] [UserCommands.cc:761] Unable to update the pose for entity id:[0], name[panda_hand]
[Err] [UserCommands.cc:761] Unable to update the pose for entity id:[0], name[panda_hand]
[Err] [UserCommands.cc:761] Unable to update the pose for entity id:[0], name[panda_hand]
[Err] [UserCommands.cc:761] Unable to update the pose for entity id:[0], name[panda_hand]
[Err] [UserCommands.cc:761] Unable to update the pose for entity id:[0], name[panda_hand]
[Err] [UserCommands.cc:761] Unable to update the pose for entity id:[0], name[panda_hand]
```

ign-omni logs
```
<same>
[Dbg] [FUSDNoticeListener.hpp:326] path /panda/panda_link7.xformOp:translate
[Dbg] [FUSDNoticeListener.hpp:326] path /panda/panda_link8.physics:angularVelocity
[Dbg] [FUSDNoticeListener.hpp:326] path /panda/panda_link8.physics:velocity
[Dbg] [FUSDNoticeListener.hpp:326] path /panda/panda_link8.xformOp:orient
[Dbg] [FUSDNoticeListener.hpp:326] path /panda/panda_link8.xformOp:translate
[Dbg] [FUSDNoticeListener.hpp:326] path /panda/panda_rightfinger.physics:angularVelocity
[Dbg] [FUSDNoticeListener.hpp:326] path /panda/panda_rightfinger.physics:velocity
[Dbg] [FUSDNoticeListener.hpp:326] path /panda/panda_rightfinger.xformOp:orient
[Dbg] [FUSDNoticeListener.hpp:326] path /panda/panda_rightfinger.xformOp:translate
[Err] [FUSDNoticeListener.hpp:450] Service call timed out
[Dbg] [FUSDNoticeListener.hpp:326] path /panda/panda_hand.physics:angularVelocity
[Dbg] [FUSDNoticeListener.hpp:326] path /panda/panda_hand.physics:velocity
[Dbg] [FUSDNoticeListener.hpp:326] path /panda/panda_hand.xformOp:orient
[Dbg] [FUSDNoticeListener.hpp:326] path /panda/panda_hand.xformOp:translate
[Dbg] [FUSDNoticeListener.hpp:326] path /panda/panda_leftfinger.physics:angularVelocity
[Dbg] [FUSDNoticeListener.hpp:326] path /panda/panda_leftfinger.physics:velocity
[Dbg] [FUSDNoticeListener.hpp:326] path /panda/panda_leftfinger.xformOp:orient
[Dbg] [FUSDNoticeListener.hpp:326] path /panda/panda_leftfinger.xformOp:translate
[Dbg] [FUSDNoticeListener.hpp:326] path /panda/panda_link1.physics:angularVelocity
[Dbg] [FUSDNoticeListener.hpp:326] path /panda/panda_link1.xformOp:orient
[Dbg] [FUSDNoticeListener.hpp:326] path /panda/panda_link1.xformOp:translate
[Dbg] [FUSDNoticeListener.hpp:326] path /panda/panda_link2.physics:angularVelocity
[Dbg] [FUSDNoticeListener.hpp:326] path /panda/panda_link2.xformOp:orient
[Dbg] [FUSDNoticeListener.hpp:326] path /panda/panda_link2.xformOp:translate
[Dbg] [FUSDNoticeListener.hpp:326] path /panda/panda_link3.physics:angularVelocity
[Dbg] [FUSDNoticeListener.hpp:326] path /panda/panda_link3.physics:velocity
[Dbg] [FUSDNoticeListener.hpp:326] path /panda/panda_link3.xformOp:orient
[Dbg] [FUSDNoticeListener.hpp:326] path /panda/panda_link3.xformOp:translate
[Dbg] [FUSDNoticeListener.hpp:326] path /panda/panda_link4.physics:angularVelocity
[Dbg] [FUSDNoticeListener.hpp:326] path /panda/panda_link4.physics:velocity
[Dbg] [FUSDNoticeListener.hpp:326] path /panda/panda_link4.xformOp:orient
[Dbg] [FUSDNoticeListener.hpp:326] path /panda/panda_link4.xformOp:translate
[Dbg] [FUSDNoticeListener.hpp:326] path /panda/panda_link5.physics:angularVelocity
[Dbg] [FUSDNoticeListener.hpp:326] path /panda/panda_link5.physics:velocity
[Dbg] [FUSDNoticeListener.hpp:326] path /panda/panda_link5.xformOp:orient
[Dbg] [FUSDNoticeListener.hpp:326] path /panda/panda_link5.xformOp:translate
[Dbg] [FUSDNoticeListener.hpp:326] path /panda/panda_link6.physics:angularVelocity
[Dbg] [FUSDNoticeListener.hpp:326] path /panda/panda_link6.physics:velocity
[Dbg] [FUSDNoticeListener.hpp:326] path /panda/panda_link6.xformOp:orient
[Dbg] [FUSDNoticeListener.hpp:326] path /panda/panda_link6.xformOp:translate
[Dbg] [FUSDNoticeListener.hpp:326] path /panda/panda_link7.physics:angularVelocity
[Dbg] [FUSDNoticeListener.hpp:326] path /panda/panda_link7.physics:velocity
[Dbg] [FUSDNoticeListener.hpp:326] path /panda/panda_link7.xformOp:orient
[Dbg] [FUSDNoticeListener.hpp:326] path /panda/panda_link7.xformOp:translate
[Dbg] [FUSDNoticeListener.hpp:326] path /panda/panda_link8.physics:angularVelocity
[Dbg] [FUSDNoticeListener.hpp:326] path /panda/panda_link8.physics:velocity
[Dbg] [FUSDNoticeListener.hpp:326] path /panda/panda_link8.xformOp:orient
[Dbg] [FUSDNoticeListener.hpp:326] path /panda/panda_link8.xformOp:translate
[Dbg] [FUSDNoticeListener.hpp:326] path /panda/panda_rightfinger.physics:angularVelocity
[Dbg] [FUSDNoticeListener.hpp:326] path /panda/panda_rightfinger.physics:velocity
[Dbg] [FUSDNoticeListener.hpp:326] path /panda/panda_rightfinger.xformOp:orient
[Dbg] [FUSDNoticeListener.hpp:326] path /panda/panda_rightfinger.xformOp:translate
```

2022-03-28 04:52 UTC, koonpeng requested changes

2022-03-28 04:52 UTC, koonpeng commented on source/ignition_live/Scene.cpp
> +    if (visualName.substr(found).find("_visual") !=
This condition will always be true since `found != std::string::npos` is true, a substr of the found index will always contain the search pattern.

2022-03-28 04:52 UTC, koonpeng commented on source/ignition_live/Scene.cpp
> +    if (linkName.substr(found).find("_link") !=
This condition will always be true since `found != std::string::npos` is true, a substr of the found index will always contain the search pattern.

2022-03-28 04:52 UTC, koonpeng commented on source/ignition_live/Scene.cpp
> +        std::cerr << "model " << _model.name() << " - " << _model.id() << '\n';
Use ign logging?

2022-03-28 04:52 UTC, koonpeng commented on source/ignition_live/Scene.cpp
> +            if (linkName.substr(found).find("_link") !=
This condition will always be true since `found != std::string::npos` is true, a substr of the found index will always contain the search pattern.

2022-03-28 04:52 UTC, koonpeng commented on source/ignition_live/Scene.cpp
> +                if (visualName.substr(found).find("_visual") !=
This condition will always be true since `found != std::string::npos` is true, a substr of the found index will always contain the search pattern.

2022-03-28 04:52 UTC, koonpeng commented on source/ignition_live/Scene.cpp
> +  for (auto const &prim : range)
Traversing the stage for each update might be bad for performance, maybe add some comments explaining a situation that will cause a model to be in multiple prims and possible improvements to avoid that.

2022-03-28 04:52 UTC, koonpeng commented on source/ignition_live/Scene.cpp
>      ignerr << "This kind of sensor [" << _sensor.type()
`ignwarn` might be more suitable.

2022-03-28 04:52 UTC, koonpeng commented on source/ignition_live/main.cpp
> +    {"issacsim", ignition::omniverse::Simulator::IssacSim}};
```suggestion
    {"isaacsim", ignition::omniverse::Simulator::IsaacSim}};
```

2022-03-28 04:52 UTC, koonpeng commented on source/ignition_live/FUSDNoticeListener.cpp
> +          q = ((q * qX) * qY) * qZ;
Since this is rotXYZ, we should be able to use the rpy constructor.

2022-03-28 04:52 UTC, koonpeng commented on source/ignition_live/FUSDNoticeListener.cpp
> +      auto modelUSD = stage->GetPrimAtPath(objectsChanged.GetParentPath());
Wasn't able to test this as I can't get the panda sim working. My only guess for joints orientation is that maybe the pose is being applied twice, first when calculating the joints position and then again here when calculating the pose?

2022-03-31 06:25 UTC, koonpeng approved these changes

2022-03-31 06:25 UTC, koonpeng commented on source/ignition_live/FUSDLayerNoticeListener.cpp
> +  std::shared_ptr<ThreadSafe<pxr::UsdStageRefPtr>> &_stage,
I guess this fixed the double lock issue? Not sure why that happens and how this fixes it, I guess the mutex got copied for some reason?

2022-03-31 07:38 UTC, merged