Added textures support to threadsafe branch
ignitionrobotics/ign-omni pull request #9
Opened 2022-02-17 21:43 UTC by ahcorde

Signed-off-by: ahcorde <ahcorde@gmail.com>

# 🎉 New feature

## Summary

Added texture support to thread-safe branch.

we are copying the images into nucleus, maybe we should use a better name for the texture paths. we can join the name of the model for example. what do you think @koonpeng ?

## Checklist
- [ ] Signed all commits for DCO
- [ ] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

2022-02-27 10:56 UTC, koonpeng requested changes
Mostly LGTM, but I didn't manage to test this, can you point me to a sdf/model with textures to test this?

2022-02-27 10:56 UTC, koonpeng commented on source/ignition_live/Material.cpp
> +    std::cerr << "The HOME environment variable was not defined, "
Use `ignerr` and properly return an error?

2022-02-27 10:56 UTC, koonpeng commented on source/ignition_live/Material.cpp
> +    }
Is this the same search locations as ign-gazebo? Is there anyway to avoid duplicated code here?

2022-02-27 10:56 UTC, koonpeng commented on source/ignition_live/Material.cpp
> +    std::cerr << "_path.c_str() " << _path.c_str() << '\n';
Use `igndbg` and `std::endl`?

2022-02-27 10:56 UTC, koonpeng commented on source/ignition_live/Material.cpp
> +    omniClientWait(omniClientCopy(
This should check for error.

2022-02-28 09:28 UTC, ahcorde commented
> Mostly LGTM, but I didn't manage to test this, can you point me to a sdf/model with textures to test this?

You can try this PR with this model from fuel https://app.ignitionrobotics.org/OpenRobotics/fuel/models/Depot

2022-03-01 01:28 UTC, koonpeng approved these changes
LGTM

2022-03-01 01:28 UTC, merged